# status: "tested"
# last_tested_version: "v1.13.2"
# platform_notes: "Tested successfully on Proxmox VM (template 902)."
# breaking_changes: none
services:
  homepage:
    image: "{{ image_name }}:{{ component_version }}"
    container_name: njorddeploy-homepage
    environment:
      - "HOMEPAGE_ALLOWED_HOSTS={{ HOMEPAGE_ALLOWED_HOSTS }}"
      - "PUID={{ PUID }}"
      - "PGID={{ PGID }}"
    ports:
      - "{{ HOMEPAGE_WEB_PORT }}:3000"
    volumes:
      - "{{ CONFIG_BASE_PATH }}/homepage/config:/app/config"
    restart: unless-stopped
    user: "0:0"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
