# status: "tested"
# last_tested_version: "24.04"
# platform_notes: "Tested successfully on Proxmox LXC."
# breaking_changes: "None"
services:
  scrypted:
    container_name: scrypted
    image: koush/scrypted:{{ component_version }}
    restart: unless-stopped
    ports:
      - "{{ PORT_SCRYPTED | default(10443) }}:10443"
    volumes:
      - "{{ CONFIG_BASE_PATH }}/scrypted:/server/volume"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
