# status: "tested"
# last_tested_version: "2026.8.1"
# platform_notes: "Tested on Proxmox LXC: docker (2026.8.1, 2026-08-29), podman (2026.8.1, 2026-08-29); Proxmox VM: docker (2026.8.1, 2026-08-29), podman (2026.8.1, 2026-08-29)."
# breaking_changes: none
services:
  esphome:
    image: "{{ image_name }}:{{ component_version }}"
    container_name: njorddeploy-esphome
    restart: unless-stopped
    environment:
      - "TZ=Europe/Amsterdam"
    ports:
      - "{{ ESPHOME_WEB_PORT }}:6052"
    volumes:
      - "{{ CONFIG_BASE_PATH }}/esphome/config:/config"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
