# status: "tested"
# last_tested_version: "10.11.18"
# platform_notes: "Tested on Proxmox LXC: docker (10.11.18, 2026-08-15), podman (10.11.18, 2026-08-15); Proxmox VM: docker (10.11.18, 2026-08-15), podman (10.11.18, 2026-08-15)."
# breaking_changes: "None"
services:
  nextcloud-db:
    image: mariadb:10.11
    container_name: nextcloud-db
    restart: always
    command: >
      --transaction-isolation=READ-COMMITTED
      --log-bin=binlog
      --binlog-format=ROW
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - njorddeploy_net
      - nextcloud-internal
    volumes:
      - "{{ NEXTCLOUD_DB_PATH | default(CONFIG_BASE_PATH ~ '/nextcloud/db', true) }}:/var/lib/mysql"
    environment:
      TZ: "{{ TZ | default('Europe/Amsterdam', true) }}"
      MYSQL_ROOT_PASSWORD: "{{ NEXTCLOUD_DB_ROOT_PASSWORD | default('nextcloudrootpass', true) }}"
      MYSQL_PASSWORD: "{{ NEXTCLOUD_DB_PASSWORD | default('nextcloudpass', true) }}"
      MYSQL_DATABASE: "{{ NEXTCLOUD_DB_NAME | default('nextcloud', true) }}"
      MYSQL_USER: "{{ NEXTCLOUD_DB_USER | default('nextcloud', true) }}"

networks:
  njorddeploy_net:
    external: true
  nextcloud-internal:
    name: nextcloud-internal
