# status: "untested"
# last_tested_version: "none"
# platform_notes: "None"
# breaking_changes: "None"
# templates/piselfhosting-docs/docker-compose.template.yml
services:
  piselfhosting-docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piselfhosting-docs
    restart: unless-stopped
    ports:
      - "8089:80" # Expose documentation on port 8089
    networks:
      - piselfhosting_net
networks:
  piselfhosting_net:
    external: true
