# status: beta
# last_tested_version: stable
# platform_notes: none
# breaking_changes: none
services:
  mosquitto:
    image: "{{ image_name }}:{{ component_version }}"
    container_name: njorddeploy-mosquitto
    restart: unless-stopped
    ports:
      - "{{ MOSQUITTO_MQTT_PORT }}:1883"
    volumes:
      - "{{ CONFIG_BASE_PATH }}/mosquitto/config:/mosquitto/config"
      - "{{ CONFIG_BASE_PATH }}/mosquitto/data:/mosquitto/data"
      - "{{ CONFIG_BASE_PATH }}/mosquitto/log:/mosquitto/log"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
