# status: "tested"
# last_tested_version: "stable"
# platform_notes: "Tested on Proxmox LXC: docker (stable, 2026-08-29), podman (stable, 2026-08-29); Proxmox VM: docker (stable, 2026-08-29), podman (stable, 2026-08-29)."
# breaking_changes: none
services:
  focalboard:
    image: "{{ image_name }}:{{ component_version }}"
    container_name: njorddeploy-focalboard
    restart: unless-stopped
    environment:
      - "FOCALBOARD_PORT=8000"
    ports:
      - "{{ FOCALBOARD_WEB_PORT }}:8000"
    volumes:
      - "{{ CONFIG_BASE_PATH }}/focalboard/data:/data"
    user: "0:0"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
