# status: "tested"
# last_tested_version: "1.22.19"
# platform_notes: "Tested on Proxmox LXC: docker (1.22.19, 2026-09-05), podman (1.22.19, 2026-09-05); Proxmox VM: docker (18.20.3, 2026-09-04), podman (1.22.19, 2026-09-05)."
# breaking_changes: "None"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - "{{ UPTIME_KUMA_DATA_PATH }}:/app/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "{{ UPTIME_KUMA_WEB_PORT }}:3001"
    restart: unless-stopped
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
