# status: "tested"
# last_tested_version: "master"
# platform_notes: "Tested on Proxmox LXC: docker (master, 2026-08-15), podman (master, 2026-08-15); Proxmox VM: docker (master, 2026-08-15), podman (master, 2026-08-15)."
# breaking_changes: "None"
services:
  octoprint:
    container_name: octoprint
    image: octoprint/octoprint:{{ component_version }}
    restart: unless-stopped
    ports:
      - "{{ PORT_OCTOPRINT | default(5000) }}:80"
    volumes:
      - "{{ CONFIG_BASE_PATH }}/octoprint:/octoprint"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
