# status: "tested"
# last_tested_version: "1.22.22"
# platform_notes: "Tested on Proxmox LXC: docker (1.22.22, 2026-09-13), podman (1.22.22, 2026-09-13); Proxmox VM: docker (1.22.22, 2026-09-13), podman (1.22.22, 2026-09-13)."
# breaking_changes: none
services:
  jellyseerr:
    image: "{{ image_name }}:{{ component_version }}"
    container_name: njorddeploy-jellyseerr
    restart: unless-stopped
    environment:
      - "LOG_LEVEL=debug"
      - "TZ=Europe/Amsterdam"
    ports:
      - "{{ JELLYSEERR_WEB_PORT }}:5055"
    volumes:
      - "{{ CONFIG_BASE_PATH }}/jellyseerr/config:/app/config"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
