# status: "tested"
# last_tested_version: "v26.4.2"
# platform_notes: "Tested on Proxmox LXC: docker (v26.4.2, 2026-08-15), podman (v26.4.2, 2026-08-15); Proxmox VM: docker (v26.4.2, 2026-08-15), podman (v26.4.2, 2026-08-15)."
# breaking_changes: "None"
services:
  homer:
    container_name: njorddeploy-homer
    image: b4bz/homer:{{ component_version }}
    restart: unless-stopped
    ports:
      - "{{ PORT_HOMER | default(8085) }}:8080"
    volumes:
      - "{{DATA_ROOT}}/homer/assets:/www/assets"
    # Homer is simple and does not need PUID/PGID/TZ
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
