# status: "tested"
# last_tested_version: "latest"
# platform_notes: "Tested successfully on Proxmox LXC."
# breaking_changes: "None"
services:
  fluffychat-web:
    container_name: njorddeploy-fluffychat-web
    build:
      context: https://github.com/HenkVanHoek/pish-fluffychat-web.git#main
      dockerfile: Dockerfile
    image: {{ image_name }}:{{ component_version }}
    pull_policy: build
    ports:
      - "{{ FLUFFYCHAT_WEB_PORT }}:80"
    environment:
      - "CHAT_MODE={{ CHAT_MODE | default('your-own-domain') }}"
      - "HOMESERVER_DOMAIN={{ HOMESERVER_DOMAIN | default('matrix.org') }}"
    restart: unless-stopped
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
