# status: "tested"
# last_tested_version: "8.2.1"
# platform_notes: "Tested on Proxmox LXC: docker (8.2.1, 2026-08-15), podman (8.2.1, 2026-08-15); Proxmox VM: docker (8.2.1, 2026-08-15), podman (8.2.1, 2026-08-15)."
# breaking_changes: "None"
services:
  web-notepad:
    container_name: njorddeploy-web-notepad
    image: "{{ image_name }}:{{ component_version }}"
    restart: unless-stopped
    ports:
      - "{{ WEB_NOTEPAD_WEB_PORT | default(8083) }}:80"
    volumes:
      - "{{DATA_ROOT}}/web-notepad/data:/var/www/html/_tmp"
    # This simple image does not need PUID/PGID or extra_hosts
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
