# status: "tested"
# last_tested_version: "0.16.1"
# platform_notes: "Tested on Proxmox LXC: docker (0.16.1, 2026-08-15), podman (0.16.1, 2026-08-15); Proxmox VM: docker (0.16.1, 2026-08-15), podman (0.16.1, 2026-08-15)."
# breaking_changes: "None"
services:
  homarr:
    container_name: njorddeploy-homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    ports:
      - "{{ HOMARR_WEB_PORT }}:7575"
    volumes:
      - "{{ HOMARR_CONFIG_PATH }}/configs:/app/data/configs"
      - "{{ HOMARR_CONFIG_PATH }}/icons:/app/public/icons"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
