# status: "beta"
# last_tested_version: stable
# platform_notes: Requires root user to bind to privileged ports like 53 (DNS).
# breaking_changes: none
services:
  adguardhome:
    container_name: njorddeploy-adguardhome
    image: "{{ image_name }}:{{ component_version }}"
    ports:
      - "{{ ADGUARDHOME_WEB_PORT }}:3000/tcp"
      - "{{ ADGUARDHOME_DNS_PORT_UDP }}:53/udp"
      - "{{ ADGUARDHOME_DNS_PORT_TCP }}:53/tcp"
      - "{{ ADGUARDHOME_DHCP_PORT_UDP }}:67/udp"
      - "{{ ADGUARDHOME_DHCP_PORT_TCP }}:68/udp"
      - "{{ ADGUARDHOME_HTTPS_PORT }}:443/tcp"
      - "{{ ADGUARDHOME_TLS_PORT }}:853/tcp"
      - "{{ ADGUARDHOME_QUIC_PORT }}:784/udp"
      - "{{ ADGUARDHOME_DNSPROXY_PORT }}:8853/tcp"
    volumes:
      - "{{ CONFIG_BASE_PATH }}/adguardhome/work:/opt/adguardhome/work"
      - "{{ CONFIG_BASE_PATH }}/adguardhome/conf:/opt/adguardhome/conf"
    restart: unless-stopped
    user: "0:0"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
