# status: "tested"
# last_tested_version: "3.11.13"
# platform_notes: "Tested on Proxmox LXC: docker (3.11.13, 2026-08-29), podman (3.11.13, 2026-08-29); Proxmox VM: docker (3.11.13, 2026-08-29), podman (3.11.13, 2026-08-29)."
# breaking_changes: none
services:
  flatnotes:
    image: "{{ image_name }}:{{ component_version }}"
    container_name: njorddeploy-flatnotes
    restart: unless-stopped
    environment:
      - "FLATNOTES_AUTH_TYPE=none"
      - "FLATNOTES_SECRET_KEY={{ FLATNOTES_SECRET_KEY }}"
    ports:
      - "{{ FLATNOTES_WEB_PORT }}:8080"
    volumes:
      - "{{ CONFIG_BASE_PATH }}/flatnotes/data:/data"
    user: "0:0"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
