# status: "tested"
# last_tested_version: "3.18.0"
# platform_notes: "Tested on Proxmox LXC: docker (3.18.0, 2026-08-29), podman (3.18.0, 2026-08-29); Proxmox VM: docker (3.18.0, 2026-08-29), podman (stable, 2026-08-29)."
# breaking_changes: none
services:
  woodpecker-ci:
    image: "{{ image_name }}:{{ component_version }}"
    container_name: njorddeploy-woodpecker-ci
    restart: unless-stopped
    environment:
      - "WOODPECKER_OPEN=true"
      - "WOODPECKER_HOST=http://localhost:9005"
      - "WOODPECKER_STORAGE_DRIVER=sqlite3"
      - "WOODPECKER_STORAGE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite"
    ports:
      - "{{ WOODPECKER_WEB_PORT }}:8000"
    volumes:
      - "{{ CONFIG_BASE_PATH }}/woodpecker/data:/var/lib/woodpecker"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
