# status: "tested"
# last_tested_version: "v3.1.0"
# platform_notes: "Tested on Proxmox LXC: docker (3.18.0, 2026-09-04), podman (22.04, 2026-09-05); Proxmox VM: docker (3.18.0, 2026-09-05), podman (v3.1.0, 2026-09-06)."
# breaking_changes: none
services:
  woodpecker-ci:
    image: "{{ image_name }}:{{ component_version }}"
    container_name: njorddeploy-woodpecker-ci
    restart: unless-stopped
    environment:
      - "WOODPECKER_OPEN=true"
      - "WOODPECKER_HOST=http://localhost:{{ WOODPECKER_WEB_PORT | default('9005') }}"
      - "WOODPECKER_STORAGE_DRIVER=sqlite3"
      - "WOODPECKER_STORAGE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite"
      - "WOODPECKER_GITEA=true"
      - "WOODPECKER_GITEA_URL=http://gitea:3000"
    ports:
      - "{{ WOODPECKER_WEB_PORT }}:8000"
    volumes:
      - "{{ CONFIG_BASE_PATH }}/woodpecker/data:/var/lib/woodpecker"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
