# status: beta
# last_tested_version: stable
# platform_notes: none
# breaking_changes: none
services:
  adguardhome:
    image: "{{ image_name }}:{{ component_version }}"
    container_name: njorddeploy-adguardhome
    ports:
      - "{{ ADGUARDHOME_WEB_PORT }}:80/tcp"
      - "{{ ADGUARDHOME_DNS_PORT_TCP }}:53/tcp"
      - "{{ ADGUARDHOME_DNS_PORT_UDP }}:53/udp"
    volumes:
      - "{{ CONFIG_BASE_PATH }}/adguardhome/work:/opt/adguardhome/work"
      - "{{ CONFIG_BASE_PATH }}/adguardhome/conf:/opt/adguardhome/conf"
    environment:
      - "TZ={{ TZ }}"
    restart: unless-stopped
    user: "0:0"
    networks:
      - njorddeploy_net

networks:
  njorddeploy_net:
    external: true
